### ISSUE TITLE
Assets won't load

### ISSUE THREAD

**Issue by valento92** [victor-gabou/vuejs-aframe-boilerplate#1]
Hi there!

Firstly, thanks for your efforts towards making a cool Vuejs+Aframe boilerplate! That's much appreciated.

So, I'm using it and there are two things: first, some dependencies seem deprecated/insecure, since I'm not an expert on webpack I just thought I'd let you know. Second, if I place a list of assets inside the scene it won't load... it throws some THREE.ObjectLoader error saying "`<!DOCTYPE html> is invalid`". Would you happen to know how to fix that?

Thanks in advance.

**Comment by valento92** [comment]
My current solution works, but I'm not sure if this is a good approach:
In my Scene component template, wrapped within <a-scene>:
`<a-assets>`
`        <a-asset-item id="arrow-obj" :src="loadAsset('models/lightblue_arrow.obj')" preload="true"></a-asset-item>`
`        <a-asset-item id="arrow-mtl" :src="loadAsset('models/lightblue_arrow.mtl')" preload="true"></a-asset-item>`
`</a-assets>`

In my Scene component methods, loadAsset is like this:
`loadAsset (asset) {`
`      return require(@/assets/${asset})`
`    }`

It's returning a require. I'm a bit confused on how this worked and am not confident this is a good approach.

**Comment by valento92** [comment]
[This](https://github.com/valento92/vuejs-aframe) is an example, check out my [latest commit](https://github.com/valento92/vuejs-aframe/commit/86ed1f6d45b19e83635dbd5aa6b334c23b528e1e).

The obj model file is perfectly fine, it works with the syntax I exaplained above.

**Comment by victor-gabou** [comment]
Like you can see in my [fork](https://github.com/victor-gabou/vuejs-aframe), moving the assets on the static folder fix your issue. I think that's it's a Vue thing

Hope it help

**Comment by valento92** [comment]
It worked! Thanks a lot for your help!

**Comment by victor-gabou** [comment]
You're welcome!
